export const DUEL_ARENA_ABI = [
  {
    type: "function",
    name: "duelCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "duels",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "playerA", type: "address" },
      { name: "playerB", type: "address" },
      { name: "entryStake", type: "uint256" },
      { name: "duration", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
      { name: "finalStateHash", type: "bytes32" },
      { name: "winner", type: "address" },
      { name: "state", type: "uint8" },
      { name: "totalPredictionPoolA", type: "uint256" },
      { name: "totalPredictionPoolB", type: "uint256" },
      { name: "traderRewardsClaimed", type: "bool" },
      { name: "playerAClaimed", type: "bool" },
      { name: "playerBClaimed", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createDuel",
    inputs: [
      { name: "duration", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "joinDuel",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "startDuel",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "placePrediction",
    inputs: [
      { name: "duelId", type: "uint256" },
      { name: "predictedWinner", type: "address" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "commitOutcome",
    inputs: [
      { name: "duelId", type: "uint256" },
      { name: "winner", type: "address" },
      { name: "stateHash", type: "bytes32" },
      { name: "priceStart", type: "uint256" },
      { name: "priceEnd", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "sigA", type: "bytes" },
      { name: "sigB", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleDuel",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimReward",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleAndClaim",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimPrediction",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelDuel",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "referee",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "DuelCreated",
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "stake", type: "uint256", indexed: false },
      { name: "duration", type: "uint256", indexed: false },
      { name: "rulesHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DuelJoined",
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "opponent", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "DuelStarted",
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "startTime", type: "uint256", indexed: false },
      { name: "endTime", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OutcomeCommitted",
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "stateHash", type: "bytes32", indexed: false },
      { name: "priceStart", type: "uint256", indexed: false },
      { name: "priceEnd", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DuelSettled",
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "traderPayout", type: "uint256", indexed: false },
      { name: "spectatorPoolPayout", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "claimant", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;
